Agda definitions generator for Actus (POC)
input-output-hk/plutus pull request #2470
Opened 2020-11-16 03:56 UTC by dk14

This is a bit proof of concept and requires further work

Pre-submit checklist:
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested
- If you updated any cabal files or added Haskell packages:
    - [ ] `$(nix-build default.nix -A pkgsLocal.updateMaterialized)` to update the materialized Nix files
   - [ ] Update `hie-*.yaml` files if needed
- If you changed any Haskell files:
   - [ ] `$(nix-shell shell.nix --run fix-stylish-haskell)` to fix any formatting issues
- If you changed any Purescript files:
   - [ ] `$(nix-shell shell.nix --run fix-purty)` to fix any formatting issues

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

2020-11-25 17:03 UTC, palas requested changes
Looks good, I think I get now why you did it this way, makes sense. Maybe it would make sense to use Template Haskell if that means that you will be able to get less Agda code and it ends up being less work when proving later.

About my review, essentially: there is one potential bug due to copy paste, and then many suggestions for function extraction

2020-11-29 04:03 UTC, dk14 commented on marlowe-actus-theory/agda/Payoff.agda
> +POF st ct ev rf y_sd_t = + 0
Of course - I only covered a single event in here, so there are many more to replace with this clause

2020-11-29 04:05 UTC, dk14 commented on marlowe-actus-theory/agda/Utils.agda
> +pseudoLt (+    m)   (+    n )  = if (m ℕ.<ᵇ n) then (+ 1) else (+ 0)
You could look at Haskell counterpart as well - it’s pseudo-boolean lessthan

2020-11-29 04:06 UTC, dk14 commented on marlowe-actus-theory/src/Language/Marlowe/ACTUS/Agda/GenStateTransition.hs
> +    , genDefinition (isc nextState) (mkFunctionName "sd") param1 params types numberType
You’re eight - overlooked this

2020-11-29 04:09 UTC, dk14 commented on marlowe-actus-theory/src/Language/Marlowe/ACTUS/Agda/GenPayoff.hs
> +    _POF_PY_PAM_PYTP_O = _POF_PY_PAM PYTP_O o_rf_CURS o_rf_RRMO _PYRT _cPYRT _CNTRL nt ipnr y_sd_t
I’ll extract those, although I can’t guarantee it would make it much more readable

2020-11-29 04:15 UTC, dk14 commented
I think if use solveZ3 - TH wouldn’t save that much work and even if it does - the work is purely mechanical. Although it would remove the annoyance of reading through stuff like “resolveNullability” :).

One other option would be to generate Agda record packing unpacking beforehead for STF functions.

2020-11-29 04:32 UTC, palas commented on marlowe-actus-theory/agda/Payoff.agda
> +POF st ct ev rf y_sd_t = + 0
Ah, cause `PY` is a constructor, I see, sorry, I thought they were all variables

2020-11-29 04:35 UTC, dk14 commented on marlowe-actus-theory/src/Language/Marlowe/ACTUS/Agda/GenPayoff.hs
> +    _POF_PY_PAM_PYTP_O = _POF_PY_PAM PYTP_O o_rf_CURS o_rf_RRMO _PYRT _cPYRT _CNTRL nt ipnr y_sd_t
It seems, agda requires explicit type-signatures for all functions

2020-11-30 14:05 UTC, michaelpj commented
(When you're getting close to happy with this we should talk a bit about how the build is set up.)

2020-12-01 10:20 UTC, dk14 commented
@michaelpj - this is a bit tricky - coz technically I need newest unreleased Agda compiler frontend for this to work. My usage case is different here from plutus as I need compiler internals - that is why build is setup this way (with stack dependency)

2020-12-01 11:33 UTC, michaelpj commented
> My use case is different here from plutus as I need compiler internals - that is why build is setup this way (with stack dependency). I use those to generate Agda code for Actus.

Yes, I understand that you're using Agda as a library. So we would then need to pull it in as a Haskell dep. However, we could then switch to using that same build of Agda for when we use it as a compiler, which saves us building it twice.

> this is a bit tricky - coz technically I need newest unreleased Agda compiler frontend for this to work (and I’ll need newest executable too in the future as it has “allow-exec” option that allows using SMT solvers).

I would prefer us to have a single version of Agda that we use for everything. If you really need an unreleased version then that might be an issue. But perhaps we could use the unreleased version for James' work too.

Could we ask the Agda folks to do a release?

2020-12-01 12:52 UTC, dk14 commented
@michaelpj I think asking Agda folks for a release (or just release date) could be a way to go. I’m doing stuff unrelated to Agda now (java :( ), so I could postpone Agda task a bit - my vacation is coming soon anyways :).

2021-03-10 19:24 UTC, gilligan commented
This hasn't been touched in quite a while - is this still relevant or can we close this PR for now?

2021-03-15 12:30 UTC, palas commented
Discontinued for now

2021-03-15 12:30 UTC, closed without merging