Restyling the dashboard.
input-output-hk/plutus pull request #2872
Opened 2021-03-17 14:02 UTC by merivale

This is a work in progress, but I want Hernan to see it before we go too much further and give ourselves more merge problems. This changes the tailwind config and `Css.purs` and `Icons.purs`, and attempts to move things closer to the target design. It also breaks the contract setup page and a few other things... But overall I think it moves things in the right direction.

2021-03-17 15:16 UTC, hrajchert commented on marlowe-dashboard-client/src/Contract/View.purs
> +          [ div [ classNames [ "py-2.5", "px-4", "flex", "items-center", "border-b", "border-lightgray" ] ]
If you changed the spacing, shouldn't these py-2.5 change as well?

2021-03-17 19:06 UTC, hrajchert requested changes
I'm sorry, I cannot merge this because it breaks the card panels I'm currently working on.

### Before

<img src="https://user-images.githubusercontent.com/2634059/111523629-40cd9580-873a-11eb-8e47-c9f9c8242fac.png" width="300">

### After

<img src="https://user-images.githubusercontent.com/2634059/111523698-5c38a080-873a-11eb-8e16-d4d22d9b3924.png" width="300">

2021-03-17 19:06 UTC, hrajchert commented on marlowe-dashboard-client/static/css/main.css
> +  min-width: 375px;
not sure this is a good idea.... this will make smaller devices to have horizontal scrolling, right?

2021-03-18 08:53 UTC, merivale commented on marlowe-dashboard-client/src/Contract/View.purs
> +                Css.secondaryButton
Okay, I'll revert this for now and leave it with you. But I'd like our buttons to always use common styles from the `Css` module.

2021-03-18 09:16 UTC, merivale commented on marlowe-dashboard-client/src/Pickup/View.purs
> +                [ classNames [ "flex", "justify-end", "mb-4", "sticky", "top-0" ] ]
🤔 You might be right. It does take up space in most of the cards I've been looking at, but not - I now see - in all of them. So when it does we can solve that with card-specific padding.

2021-03-18 14:57 UTC, merivale commented on marlowe-dashboard-client/src/Play/View.purs
> +    cardWrapperClasses = case mCard of
Yeah, this was unfinished business, which I've tidied up now. The wrapper with padding ensures a minimum left/right margin, and allows the card to be full width on small screens (also avoiding the need - that I was briefly worried about - for fixing the minimum size of the screen).

2021-03-18 14:57 UTC, merivale commented on marlowe-dashboard-client/src/Play/View.purs
> +                  [ classNames [ "flex", "justify-end", "mb-4", "sticky", "top-0" ] ]
as above 👍

2021-03-18 14:59 UTC, merivale commented on marlowe-dashboard-client/tailwind.config.js
> +    backgroundColor: ['hover', 'disabled'],
leaving this for now, but let's discuss it and think about changing it later

2021-03-19 19:29 UTC, hrajchert approved these changes

2021-03-19 19:29 UTC, merged