Russ/marlowe finance redesign
input-output-hk/plutus pull request #3579
Opened 2021-07-19 15:33 UTC by RussellHepton

These are the first defining changes to the Marlowe home page website redesign.

Pre-submit checklist:
- Branch
    - [X] Commit sequence broadly makes sense
    - [X] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [X] Self-reviewed the diff
    - [X] Useful pull request description
    - [X] Reviewer requested

Pre-merge checklist:
- [ ] Someone approved it
- [ ] Commits have useful messages
- [ ] Review clarifications made it into the code
- [ ] History is moderately tidy; or going to squash-merge

2021-07-23 14:16 UTC, hrajchert requested changes

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +        {# Defines the margins #}
unneeded comment

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +            <img loading="lazy" class="w-2/3 mx-auto lg:pb-0 md:pb-8 pb-8 block md:hidden" src="{% static './static/img/tabs-mobile.jpg' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +              <img loading="lazy" class="w-full mx-auto" src="{% static './static/img/run-video-thumbnail.png' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +      <img loading="lazy" class="section-circle-bottom-left invisible lg:visible" src="{% static './static/img/circle-bottom-left.svg' %}" alt="xx">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +    <!--S1 - Marlowe Run-->
the comments are a little misleading, is this marlowe run or build section?

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +          <div class="lg:w-10/12 w-11/12 self-center justify-self-center">
are you using `w-10/12` and `11/12` for margins? if so please change to use proper margins.

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +            <div class="relative md:w-5/6 w-11/12 md:mt-14 mt-8">
same comment about margins and width here

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +                <img loading="lazy" class="w-32 absolute left-52 bottom-2 xl:block hidden" src="{% static './static/img/arrow-light.svg' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +            <img loading="lazy" class="lg:w-11/12 md:w-3/4 w-11/12 lg:h-80 md:h-80 h-60 object-cover mx-auto" src="{% static './static/img/blockly.gif' %}" alt="">
same width and margin comment
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +          <!--<div class="lg:row-start-auto row-start-1"> <img loading="lazy" class="w-full" src="{% static './static/img/marlowe-blockly-blocks.png' %}" alt=""> </div>-->
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +              <img loading="lazy" class="w-full mx-auto" src="{% static './static/img/marlowe-build-video-thumbnail.png' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +          <div class="w-11/12 mx-auto my-10 shadow-lg h-auto rounded-lg" style="background-color:#232d3d;">
if that colour is not already present, you should add it to our colour pallete

https://tailwindcss.com/docs/customizing-colors

and then use `bg-custom-colour`

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +          <div class="w-11/12 mx-auto my-10 shadow-lg h-auto rounded-lg" style="background-color:#232d3d;">
also `w-11/12` for margins and `mx-auto` for centering should be changed for `mx-{val}`for margin and `flex justify-center` for centering.

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +              <img loading="lazy" class="w-24 float-left" src="{% static './static/img/marlowe-build-dark.svg' %}" alt="">
float-left sounds fishy

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +              <img loading="lazy" class="w-24 float-left" src="{% static './static/img/marlowe-build-dark.svg' %}" alt="">
also alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +            <img loading="lazy" class="md:w-96 w-72 pl-5 py-5 object-cover" src="{% static './static/img/marlowe-code.gif' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +          <!--<div class="" style=""> <img loading="lazy" class="" src="{% static './static/img/marlowe-build-code-module.png' %}" alt=""> </div>-->
remove comments

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +          <div class="lg:w-10/12 w-11/12 mb-0 md:mt-0 mt-0 md:mb-0 lg:-mx-0 mx-auto lg:justify-self-center self-center" style="">
width and margin issue

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +            <div class="relative md:w-5/6 w-11/12">
width instead of margin

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +                <img loading="lazy" class="w-32 absolute left-52 bottom-2 xl:block hidden" src="{% static './static/img/arrow-light.svg' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +      <img loading="lazy" style="" class="section-m-top-right absolute invisible lg:visible w-full" src="{% static './static/img/marlowe-background-m.svg' %}" alt="xx">
invisible still occupies space, use hidden instead

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +            <div class="relative mx-auto md:w-5/6 w-11/12 md:mt-18 md:mb-5 mt-12">
width margin and centering issue

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +                  <img loading="lazy" class="w-32 absolute -right-36 bottom-6 xl:block hidden" src="{% static './static/img/arrow-light.svg' %}" alt="">
alt text

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +        <!--Row-->
remove comments

2021-07-23 14:16 UTC, hrajchert commented on marlowe-website/src/index.njk
> +      <img loading="lazy" style="" class="pink-m-right invisible lg:visible" src="{% static './static/img/pink-m-right.svg' %}" alt="xx">
invisible still occupies space, also alt text

2021-07-30 09:48 UTC, RussellHepton commented on marlowe-website/src/index.css
> +}
height: {
        logo: "100px",
        "logo-wider": "85px",
      },

2021-07-30 09:51 UTC, RussellHepton commented on marlowe-website/src/index.css
> +  border-bottom: 4px solid #273245;
:( Returns "Failed to compile" in browser refresh

2021-07-30 09:57 UTC, RussellHepton commented on marlowe-website/src/index.css
> +  width: 300px;
Changed to: 

.section-circle-top-right {
  position: absolute;
  @apply w-80;
  right: 0;
  top: 0;
  z-index: 0;
}

2021-07-30 10:03 UTC, RussellHepton commented on marlowe-website/src/index.css
> +}
Changed the config file to include a new width property
      width: {
        pinkM: "280px",
      },

2021-07-30 10:05 UTC, RussellHepton commented on marlowe-website/src/index.css
> +}
.pink-m-left,
.pink-m-right {
  position: absolute;
  left: 0;
  top: 0;
  z-index: 0;
  opacity: 0.8;
}

2021-07-30 10:16 UTC, RussellHepton commented on marlowe-website/src/index.css
> +}
Not quite the same, but maybe this is better? 
.pink-m-left,
.pink-m-right {
  position: absolute;
  z-index: 0;
  opacity: 0.8;
}

.pink-m-left {
  left: 0;
  top: 0;
}

.pink-m-right {
  right: 0;
  bottom: 0;
}

2021-08-25 14:11 UTC, merged