Update Marlowe tutorial and fix ZCB example
input-output-hk/plutus pull request #3820
Opened 2021-08-27 15:50 UTC by simonjohnthompson

First phase of revision of Marlowe tutorial. Revised all sections but 9 and 11, which concern the playground.

2021-08-30 07:53 UTC, nahern approved these changes
approved

2021-09-07 20:58 UTC, palas requested changes
That looked like a lot of work. I have found a few typos that I marked.
I think the CI fails because `purescript` examples need to be changed too, I will do that next

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/playground-overview.rst
> +There is no need for you to add these fields yourself, ans they are generated automatically from the contract as
I would say something along the lines of: "When a contract is compiled successfully, the metadata editor will prompt you to add metadata for the fields that correspond to the appropriate elements of the contract, and to delete the fields that do not correspond to anything in the contract."

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/playground-overview.rst
> +it is developed.
Same thing here

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/playground-overview.rst
> +to reflect that fact that the initial deposit and pay have been performed.
`that fact that -> the fact that`

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/marlowe-model.rst
> +on chain we will use time, adopting the Posix time standard.
I think it is usually written all-caps: `POSIX`

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/marlowe-data.rst
> +same show/overload approach as used above, they will appear in contracts  numbers:
I think the `as` before numbers is still necessary, also the two `:` in a row are a bit strange, maybe `;` was better

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/marlowe-data.rst
> +constructors, giving selectors for the data as used above, well as used above, making in clearer
This is garbled, also I just noticed that: `making in clearer -> making it clearer`

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/marlowe-data.rst
> +The endpoints of the interval are accessible as used above, the values
Probably needs another `as` or something like that, maybe it would be best to put `as used above` in parenthesis

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/introducing-marlowe.rst
> +-  `The Marlowe Website <https://hernan.marlowe-web.iohkdev.io/#>`_ landing page for all things Marlowe.
Not sure we should point at Hernán's deployment

2021-09-07 20:58 UTC, palas commented on doc/marlowe/tutorials/javascript-embedding.rst
> +its source code here. https://github.com/input-output-hk/plutus/blob/master/marlowe-playground-client/src/Language/Javascript/MarloweJS.ts
`. -> :`

2021-09-08 13:03 UTC, palas approved these changes

2021-09-08 14:44 UTC, simonjohnthompson reviewed
Agree with all of these. Thanks.

2021-09-08 15:52 UTC, merged